### ISSUE TITLE
A few songs not downloading.

### ISSUE THREAD

**Issue by Lv99Pangolin** [Tenpi/soundcloud-extension#4]
A few songs aren't downloading from a particular artist. I dunno if it's my computer or if something's wrong with the extension. It does the loading thing and then nothing happens. An artist called Hotline Sehwani is where the problem keeps popping up if you wanna test it. It works for others, but not for his for some reason.

**Comment by Tenpi** [comment]
Hello, it's because that artist uses characters in the title that are invalid for filenames, such as the zero-width space. It should be fixed as of `v0.2.3`. It should be available on the Chrome/Firefox stores in a few hours, or you can get it directly here: https://github.com/Tenpi/soundcloud-extension/releases

**Comment by Lv99Pangolin** [comment]
Yo, dude, that's awesome! Thank you so much. I love the extension btw, if I
haven't said it already.
